### ISSUE TITLE
problem by running

### ISSUE THREAD

**Issue by montes2012** [rongchaplin/laravel-crud-generator#1]
problem by running composer require t73biz/crud-generator

I get Error:

[InvalidArgumentException]  
  Could not find package t73biz/crud-generator at any version for your minimu  
  m-stability (stable). Check the package spelling or your minimum-stability

**Comment by t73biz** [comment]
Hi there.
Can you give me the exact command that you are using and also a [gist](https://gist.github.com/) of your composer.json so that I may be able to help you better?

**Comment by t73biz** [comment]
Actually I have found the issue
It's in the documentation. I will fix immediately.

The command should be : 

``` bash
composer require t73biz/laravel5-crud-generator
```
