### ISSUE TITLE
Could not find package t73biz/crud-generator at any version for your minimum-stability

### ISSUE THREAD

**Issue by Dunebook** [rongchaplin/laravel-crud-generator#2]
This seemed too good to be true and actually was. I tried to install crud-generator and got this in response: [InvalidArgumentException]
Could not find package t73biz/crud-generator at any version for your minimum-stability (
stable). Check the package spelling or your minimum-stability
Please let me know if you know how to fix it

**Comment by t73biz** [comment]
There was an issue with the documentation previously. It has been fixed now. 

```
composer require t73biz/laravel5-crud-generator
```

**Comment by Dunebook** [comment]
oh thanks --- actually visitors of site pointed out this issue http://dunebook.com/generate-crud-directly-via-command-line-in-laravel/ btw thanks
